### ISSUE TITLE
What do I do with the newGameLib folder?

### ISSUE THREAD

**Issue by brickomania** [DrDab/blender-osgjs-loader#6]
Tried copying it in different places- blender folder, python folders, etc. keep getting an error on line 3 saying "ImportError: No module named newGameLib. How do I fix this? I'm new to blender and have very little idea what I'm doing.

**Comment by actioncircus** [comment]
I had that problem too but I almost figured it out. I used python 2.6.1 (the python version blender 2.49 uses) and set the environment variables to C:\Python26; C:\Python26\DLLs; C:\Python26\Lib; C:\Python26\Lib\lib-tk

![example26](https://user-images.githubusercontent.com/79541266/108915044-4d0e7900-75fa-11eb-866a-45ffba5e7a1d.png)
In the end, only part of the model imported and the script had a line error. Other people have found problems and I agree that this (current version by DrDab) simply just doesn't work.

**Comment by actioncircus** [comment]
I uploaded a version that works https://github.com/actioncircus/Blender-osgjs-importer

**Comment by DrDab** [comment]
Yep, others should use that one. This repo is abandoned until further notice.
